version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    expose:
      - '3306'
    volumes:
      - type: volume
        source: mysql_var
        target: /var/lib/mysql
      - type: volume
        source: mysql_etc
        target: /etc/mysql
    networks:
      - mysql
volumes:
  mysql_var:
    name: mysql_var
  mysql_etc:
    name: mysql_etc

networks:
  mysql:
    name: mysql 
    driver: bridge
